[pytest]
markers =
    smoke: Smoke test cases
    sanity: Sanity test cases
    regression: Regression test cases
    e2e : end to end test


; """
; [pytest]

; addopts = -v -s --html=Reports/report.html

; testpaths = Test_cases

; markers =
;     smoke: Smoke tests
;     regression: Regression tests
;     sanity: Sanity tests

; python_files = test_*.py

; python_classes = Test*

; python_functions = test_*""